version: '3.4'

services:

  tododb:
    container_name: tododb

    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=api_todo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

    
  pgadmin:
    container_name: pgadmin
    environment: 
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80"
    
#   catalog.api:
#     container_name: catalog.api
#     environment:
#       - ASPNETCORE_ENVIRONMENT=Development
#       - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
#     depends_on:
#       - catalogdb
#     ports:
#       - "8000:80"
    
 

 