version: '3.4'

services:
  
  tododb:
    image: postgres
  
  pgadmin:
    image: dpage/pgadmin4

  # catalog.api:
  #   image: ${DOCKER_REGISTRY-}catalogapi
  #   build:
  #     context: .
  #     dockerfile: Catalog.API/Dockerfile
  
  
volumes:
  postgres_data:
  pgadmin_data: